### PR TITLE
add guide for writing Coder images

### PR DESCRIPTION
**Pull request by bpmct**
This is still a draft, but I wanted to get started on a guide that covers how to add common elements (such as an IDE, VS Code extension, or git repository) to a Coder image.

I also wanted to mention Coder's example images repo, as well as how sysbox is necessary to build images for CVMs. This may be better suited in the "Guides" section, and it definitely needs some editing. Any thoughts @khorne3?

### CODE REVIEW

**Comment by bpmct** [comment]
@IAmHughes any idea why this didn't trigger an action? I'd also love your 👀  on this doc :)

**Comment by bpmct** [comment]
FYI this is being put on hold for now pending some new guides sections and incoming docs from help.coder.com

**Comment by IAmHughes** [comment]
> @IAmHughes any idea why this didn't trigger an action? I'd also love your 👀 on this doc :)

Wanted to reply to this now that I'm back from the storm outage. I know this is on hold for now, but an initial pass I think this looks good. We may need to change some headers and/or positioning/ordering but it's a great start.

As for the action trigger...no clue....that's the issue I was having that I never fixed on my branch 😢 

Taking a look at the file, I wonder if the indentation is messing up the `YAML`, since [this is too indented](https://github.com/cdr/docs/blob/master/.github/workflows/preview.yaml#L7-L9).

I'll open a PR now to fix the indentation.

**Comment by khorne3** [comment]
@bpmct I'm planning to work on this. We have a modest config file, so I'm going to move the config examples there and keep the rest in the guides (or maybe even move to Images)

**Pull request closed without merging**
