### PR TITLE
Add Okta OIDC Guide

### PR DESCRIPTION
**Pull request by IAmHughes**
This PR adds the Okta OIDC guide for creating an app to use OIDC with Okta and Coder.

### CODE REVIEW

**Comment by IAmHughes** [comment]
This is ready for review. For some reason, the deploy preview seems broken for the `Docs` tab and I'm not sure why? @bpmct or @ericpaulsen do you know?

**Comment by ericpaulsen** [comment]
LGTM - only thing I'd recommend adding is context around Okta groups & users being already able to access Coder. No need to manually add users on the Coder side.

**Comment by IAmHughes** [comment]
> Okta groups & users being already able to access Coder. No need to manually add users on the Coder side.

I'm not sure what you mean @ericpaulsen? Within Okta, if no one is assigned the application (step 3 in the guide), no one can access Coder.

**Comment by ericpaulsen** [comment]
Yes - my comment assumed that such groups & users would be assigned to the application. Apologies for the lack of clarity.

**Comment by IAmHughes** [comment]
Any ideas on the `Docs` tab not working in the preview deployment @ericpaulsen ?

**Comment by ericpaulsen** [comment]
Not sure. I'm not familiar with debugging the Vercel preview. In my experience, issues with the preview aren't typically indicative of an issue with the commit once merged.

**Review by ericpaulsen — APPROVED** [review]

**Comment by vapurrmaid** [comment]
@all-contributors please add @IAmHughes  for bug, content, idea

**Pull request merged**
