### PR TITLE
fix: command formatting

### PR DESCRIPTION
**Pull request by ericpaulsen**
small change to add code formatting to the helm command.

### CODE REVIEW

**Review by vapurrmaid — COMMENTED** [review]
I know this may seem like overkill to some, but I have a preference towards using code blocks for almost all code cases like this, as it the way the structure flows is visually appealing and really draws attention to the comand.

> you can run
>
> ```bash
> helm uninstall coder
> ```
> ....lorem ipsum and so on


See Above ^

**Comment by ericpaulsen** [comment]
> I know this may seem like overkill to some, but I have a preference towards using code blocks for almost all of these cases. The structural flow is visually appealing and draws attention to the command.
> 
> > you can run
> > ```shell
> > helm uninstall coder
> > ```
> > 
> > 
> > ....lorem ipsum and so on
> 
> See Above ^

I see what you're saying, although it might look a bit funky when creating a code block in an indented text section. I'll submit a second commit to see what it looks like in preview.

**Comment by ericpaulsen** [comment]
Thoughts?

**Comment by vapurrmaid** [comment]
> Thoughts?

You're right, it didn't render as expected/as nicely. I think let's just go with what you originally had - sorry for throwing for a loop!

**Comment by ericpaulsen** [comment]
> > Thoughts?
> 
> You're right, it didn't render as expected/as nicely. I think let's just go with what you originally had - sorry for throwing for a loop!

No worries! Appreciate the diligence.

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
