### PR TITLE
add steps for installing coder in an archive

### PR DESCRIPTION
**Pull request by ericpaulsen**
adding steps for pulling down the helm chart & installing Coder in an archive, as a customer has run into this issue. @sreya provided the steps (included in this PR) as a solution to the customer.

### CODE REVIEW

**Comment by khorne3** [comment]
@ericpaulsen How common is this? I'm wondering if we should turn this into a brief guide and link out to it?

**Comment by ericpaulsen** [comment]
> @ericpaulsen How common is this? I'm wondering if we should turn this into a brief guide and link out to it?

Not very common from my personal experience. Since it's only a few steps I think we can just keep it in the install steps for easy reference.

**Comment by khorne3** [comment]
I think, given that the install process is challenging enough as is, we should move it out -- it's short, but I could see this being confusing for people. I'd be happy to do this

**Comment by ericpaulsen** [comment]
That sounds good with me. Thanks for taking it on.

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
