### PR TITLE
Replace helm command with upgrade and specify repo

### PR DESCRIPTION
**Pull request by IAmHughes**
This replaces the command we call out in the `devurls` setup as we are saying we are modifying helm, but then run the `install` command. This changes it to an `upgrade`, and adds the repo.

### CODE REVIEW

**Review by khorne3 — APPROVED** [review]

**Comment by IAmHughes** [comment]
Hmmm, looks like the deploy failed in fetching a sha. 🤔

**Comment by kylecarbs** [comment]
@IAmHughes merge master in, it'll fix the preview!

**Comment by IAmHughes** [comment]
When viewing the preview deployment, clicking `Docs` in the navbar gives me a 502. Is that expected? First time doing a PR to the docs so wasn't sure on that end.

/cc @kylecarbs @khorne3

**Comment by khorne3** [comment]
I _think_ this is the problem: https://github.com/cdr/docs/pull/73/files

**Review by deansheather — APPROVED** [review]

**Pull request merged**
