### PR TITLE
recommend default formatter and auto-format on save

### PR DESCRIPTION
**Pull request by bpmct**
This repository recommends the `davidanson.vscode-markdownlint` extension and prompts the user to install it when they first clone the docs repo. However, the formatter will do nothing unless people set it to their default formatter and intermittently use the "format" command in the command palette or a keyboard shortcut.

This proposed PR will (for all users editing the docs with VS Code):
- set `davidanson.vscode-markdownlint` as the default formatter for this repo
- auto format (with this `davidanson.vscode-markdownlint`) whenever a file is saved

This should also lead to less linting issues from new contributors

Alternatives:
- document how someone can do this themselves on the README

I use the "prettier" extension for other projects and, while it always passes lint tests, it will try to "re-format" some docs. I found the issue was my default formatter wasn't set (or was reset) for this repo.

### CODE REVIEW

**Comment by bpmct** [comment]
@khorne3 does markdownlint automatically fix your line errors for you? Prettier did this for me but with markdownlint I am finding that I have to manually decide when to break a line which feels a bit awkward and clunky. 

Screen Shot 2021-07-26 at 9 52 37 AM

**Comment by khorne3** [comment]
@bpmct I'm using Rewrap to automatically add linebreaks because mdlint doesn't

**Comment by bpmct** [comment]
> @bpmct I'm using Rewrap to automatically add linebreaks because mdlint doesn't

Is it [stkb.rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap)? Are there any VS Code settings you use to "rewrap" on save we can add here?

**Comment by khorne3** [comment]
Yup, that's the one. I checked my JSON file and all I have is `"rewrap.autoWrap.enabled": true,` (top level)

**Review by vapurrmaid — APPROVED** [review]

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
