### PR TITLE
chore: add instructions for using Code With Me

### PR DESCRIPTION
**Pull request by khorne3**

### CODE REVIEW

**Review by vapurrmaid — APPROVED** [review]

**Comment by BrunoQuaresma** [comment]
FYI: Please do not merge yet, the build is broken!

**Review by vapurrmaid — COMMENTED** [review]
@khorne3 - seeing this:

> Build error occurred
  Error: no title specified for: workspaces/code-with-me.md
      at /vercel/path0/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:3227:15
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 4)
      at async /vercel/path0/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:3213:20
      at async Promise.all (index 1)
      at async parseManifest (/vercel/path0/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:3236:3)
      at async getCoderDocsStaticPaths (/vercel/path0/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:3313:26)
      at async Promise.all (index 0)
      at async getStaticPaths (/vercel/path0/product/coder.com/site/.next/server/pages/docs/[[...slug]].js:3456:49) {
    type: 'Error'
  }

**Comment by vapurrmaid** [comment]
Looks like Bruno fixed it - lowercasing `Title` and `Description`

**Comment by BrunoQuaresma** [comment]
@khorne3 I noticed the code-with-me was using capitalized Title and Description. To make it work, I made them lower case as the other files, is that ok?

**Comment by khorne3** [comment]
@BrunoQuaresma Yes that is fine! My mistake :(

**Pull request merged**
