### PR TITLE
fix: home directory

### PR DESCRIPTION
**Pull request by ericpaulsen**
updating from `home/<username>` to `home/coder`

### CODE REVIEW

**Comment by cmoog** [comment]
Isn't the existing language is correct? Different images have different users.

**Comment by ericpaulsen** [comment]
> Isn't the existing language is correct? Different images have different users.

Ah you're right - I thought we used the user's Coder username as part of the home directory in previous versions, so I thought it was outdated. Makes sense that it is set on the image. Should we clarify that `<username` is set in the image?

**Comment by vapurrmaid** [comment]
> > Isn't the existing language is correct? Different images have different users.
> 
> Ah you're right - I thought we used the user's Coder username as part of the home directory in previous versions, so I thought it was outdated. Makes sense that it is set on the image. Should we clarify that `<username>` is set in the image?

I think we can mention it. In our development image, the last line is:

```dockerfile
USER coder
```

For example in the below section: https://coder.com/docs/environments/lifecycle#rebuilds

We could have a 

> **Note**: `username` is defined in an image. See <https://docs.docker.com/engine/reference/builder/#user>

**Comment by cmoog** [comment]
Oh I see where confusion is coming from. Yeah that all sounds good to me.

**Review by vapurrmaid — APPROVED** [review]

**Pull request merged**
