### PR TITLE
feat: Add changelog

### PR DESCRIPTION
**Pull request by vapurrmaid**

### CODE REVIEW

**Comment by vapurrmaid** [comment]
Seems preview action is not being triggered, so here's a rough preview from my local setup:

Screenshot from 2021-01-07 00-17-45

Screenshot from 2021-01-07 00-18-54

**Comment by nathanpotter** [comment]
beautiful 🎉

**Comment by vapurrmaid** [comment]
Going ahead on this one

**Comment by rachelchhay** [comment]
Looks great!

**Review by kylecarbs — APPROVED** [review]
It'd be neat to put the description as the release date

**Pull request merged**
