### PR TITLE
chore: update GPUs info

### PR DESCRIPTION
**Pull request by khorne3**

### CODE REVIEW

**Comment by khorne3** [comment]
@deansheather Underneath the text I updated, it says:

>By default, Coder allocates resources (CPU cores, memory, and disk space)
>based on the parent image.

Should I change this list of resources to include GPUs as well?

**Comment by deansheather** [comment]
@khorne3 Images don't have GPUs as a default resource option, so we should leave it as is.

**Review by deansheather — APPROVED** [review]
Looks good but you should replace the picture with one that has a `0` in the GPU box. There was a PR that made sure there was a 0 there by default, but it hasn't been deployed yet.

**Comment by vapurrmaid** [comment]
> Looks good but you should replace the picture with one that has a `0` in the GPU box. There was a PR that made sure there was a 0 there by default, but it hasn't been deployed yet.

We can easily do this in the web console - I'll message @khorne3 on Slack

**Review by vapurrmaid — APPROVED** [review]

**Pull request merged**
