### PR TITLE
chore: edit changes to docs

### PR DESCRIPTION
**Pull request by khorne3**
Docs affected:

* Compute Resources ~(also moved this out of admin since it's a concept doc)~
* SSH
* Editors and IDE

### CODE REVIEW

**Comment by cmoog** [comment]
Let's get a process for adding redirects so we don't break these links

**Comment by khorne3** [comment]
@cmoog I was told I could add entries to [this](https://github.com/cdr/m/blob/6f3e3490afd5201590aede068639b07be0798604/product/coder.com/vercel.json) for redirects; is that not the case or is there a better way?

**Comment by cmoog** [comment]
Oh that works great, nice 👍

**Review by cmoog — APPROVED** [review]
Great changes 👍

**Pull request merged**
